### PR TITLE
Fix listing and using the MIG device handler

### LINKED ISSUE #1293: In `GetGPUPower()`, Kepler should use the per GPU Power consumption to calculate the process's how much power consumed by the process
### What would you like to be added?

Here is the [current implementation](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/model/estimator/local/ratio.go#L168). It takes into account of all the GPU power from every devices and attributes regardless of their differences. 

```go
// GetComponentsPower returns GPU Power in Watts associated to each each process/process/pod
func (r *RatioPowerModel) GetGPUPower(isIdlePower bool) ([]float64, error) {
	nodeComponentsPowerOfAllProcesses := []float64{}

	// the number of processes is used to evernly divide the power consumption for OTHER and UNCORE
	// we do not use CPU utilization for OTHER and UNCORE because they are not necessarily directly
	numProcesses := float64(r.xidx)

	// estimate the power for each process
	for processIdx := 0; processIdx < r.xidx; processIdx++ {
		var processPower float64

		// TODO: idle power should be divided accordinly to the process requested resource
		if isIdlePower {
			processPower = r.nodeFeatureValues[GpuIdlePower] / numProcesses
		} else {
			processPower = r.getPowerByRatio(processIdx, int(GpuUsageMetric), int(GpuDynPower), numProcesses)
		}
		nodeComponentsPowerOfAllProcesses = append(nodeComponentsPowerOfAllProcesses, processPower)
	}
	return nodeComponentsPowerOfAllProcesses, nil
}
```

### Why is this needed?

We should get per GPU power and attribute only to those processes that use this GPU.

### PR DESCRIPTION
**Pull request by marceloamaral**
The current code is not listing and getting the process in the MIG device handler.

This code get the MIG device handler and store only the necessary data.

### CODE REVIEW

**Comment by rootfs** [comment]
> To fix the problem in https://github.com/sustainable-computing-io/kepler/issues/1293, we need to index the process GPU utilization with the parent GPU ID (not with the MIG ID). This way, the Ratio power model can correctly distribute the parent GPU power consumption among the processes in the MIG slices based on their GPU utilization.

I don't think this is sufficient. The problem in #1293 is about multiple GPUs. Each GPU may report different energy readings. The current ratio model uses aggregate utilization and energy among multiple GPU devices, this leads to problems when the GPUs are configured differently in terms of cooling, frequency, and SM spec.

**Comment by marceloamaral** [comment]
@rootfs, you're correct. 

Even if we calculate the MIG power before applying the Ratio Power Model, we'll still face this issue that the Ratio Power model uses the aggregated system data....

Can we merge this PR and fix the problem to calculate the Ratio Per GPU later?

**Comment by marceloamaral** [comment]
@rootfs, you're correct.

This PR does not fix the problem in #1293

This PR fix some other problems.

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@marceloamaral let's merge this one first. When you have time, can you also fix the multi GPU ratio in #1292?

**Pull request merged**
