### PR TITLE
dockerfile: allow nvidia-smi in the container image

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by rootfs** [comment]
cc @vimalk78

**Review by vimalk78 — APPROVED** [review]
lgtm

**Comment by vimalk78** [comment]
@rootfs include this is with tech preview?

**Comment by rootfs** [comment]
@vimalk78 that'll be great. Can you port it? thanks

**Comment by vimalk78** [comment]
added to tech-preview

**Pull request merged**
