### PR TITLE
nit: remove GPUStats to avoid confusion as it's not used at all

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
found this during other dev item ..

**Comment by marceloamaral** [comment]
I believe we should not remove the GPU statistics since processes can utilize the GPU and it contributes to the overall power consumption.

**Comment by jichenjc** [comment]
>>>I believe we should not remove the GPU statistics since processes can utilize the GPU and it contributes to the overall power consumption.

it is not used anywhere, I try to find GPU metrics and found this, then search but seems no where update this value or set it

**Review by marceloamaral — APPROVED** [review]
Right, the `GPUStats` is never used.

The GPU metrics are updated in `CounterStats` as in pkg/collector/container_accelerator_collector.go:L65

**Pull request merged**
