### PR TITLE
Add UT for ReadLineKEqualToV

### PR DESCRIPTION
**Pull request by jichenjc**
Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

### CODE REVIEW

**Comment by jichenjc** [comment]
```
clusterrole.rbac.authorization.k8s.io/kepler-clusterrole created
clusterrolebinding.rbac.authorization.k8s.io/kepler-clusterrole-binding created
serviceaccount/kepler-sa created
daemonset.apps/kepler-exporter created
service/kepler-exporter created
servicemonitor.monitoring.coreos.com/kepler-exporter created
clusterrole.rbac.authorization.k8s.io/prometheus-k8s created
role.rbac.authorization.k8s.io/prometheus-k8s created
rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
+ kubectl rollout status daemonset kepler-exporter -n kepler --timeout 60s
Waiting for daemon set "kepler-exporter" rollout to finish: 0 of 1 updated pods are available...
error: timed out waiting for the condition
make: *** [Makefile:173: cluster-sync] Error 1
```

@SamYuan1990 @rootfs I saw some PR saying integration test flaky, seems I encounter this again
do we have any logs for the CI ? e.g the container status , container logs etc?

**Comment by marceloamaral** [comment]
I don't think we're saving the logs right now, but we can get the logs and pod description if it fails and dump to stdot....

Although I'm not sure what the problem is, it could be timeout related
But before increasing the timeout we need to dump the logs when it fails for checking the root cause

**Review by rootfs — APPROVED** [review]

**Comment by SamYuan1990** [comment]
> ```
> clusterrole.rbac.authorization.k8s.io/kepler-clusterrole created
> clusterrolebinding.rbac.authorization.k8s.io/kepler-clusterrole-binding created
> serviceaccount/kepler-sa created
> daemonset.apps/kepler-exporter created
> service/kepler-exporter created
> servicemonitor.monitoring.coreos.com/kepler-exporter created
> clusterrole.rbac.authorization.k8s.io/prometheus-k8s created
> role.rbac.authorization.k8s.io/prometheus-k8s created
> rolebinding.rbac.authorization.k8s.io/prometheus-k8s created
> + kubectl rollout status daemonset kepler-exporter -n kepler --timeout 60s
> Waiting for daemon set "kepler-exporter" rollout to finish: 0 of 1 updated pods are available...
> error: timed out waiting for the condition
> make: *** [Makefile:173: cluster-sync] Error 1
> ```
> 
> @SamYuan1990 @rootfs I saw some PR saying integration test flaky, seems I encounter this again do we have any logs for the CI ? e.g the container status , container logs etc?

github action has a debug mode, but I don't think the debug mode will logging k8s resources.
ref to
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
I suppose even if a step breaks in the middle will not allow us to download a middle file?

**Comment by jichenjc** [comment]
>>>I suppose even if a step breaks in the middle will not allow us to download a middle file?

I think `describe` pod and logs pod should give at least some clue on what's going on here
if it's still working , then increase the timeout otherwise fix potential issue

**Pull request merged**
