### PR TITLE
Remove unit test in macOS

### PR DESCRIPTION
**Pull request by marceloamaral**
Fix the issue #346

We don't need to run the test in macOS environment,  since we can run the tests in container while using a macOS.

### CODE REVIEW

**Comment by SamYuan1990** [comment]
https://github.com/sustainable-computing-io/kepler/pull/345/files#r1009406770
I don't suppose it is an issue for MacOS.

**Comment by SamYuan1990** [comment]
or say, as our GPU code relays on `NVIDIA` package.
Hence we have issue with
- no GPU case but has to install NVIDIA package?
- no NVIDIA GPU has to install NVIDIA GPU package?

hence, just remove MacOS test case code is not targeting on root cause of #346

**Comment by SamYuan1990** [comment]
> @SamYuan1990
> 
> I didn't understand what you think the problem is... Could you explain more?
> 
> I'm having the same problem on my macOS, but I can compile the code in containers....

will NVIDIA GPU package is installed on containers but not MacOS. as line 

https://github.com/sustainable-computing-io/kepler/blob/bf17c6bfa1062e4d557d0aeb1ce2ffc67ade803e/build/Dockerfile.base#L21

but on MacOS, by default, we don't install this package, hence when a golang code invokes `	"github.com/NVIDIA/go-nvml/pkg/nvml"` on MacOS, or **any instance without this library been installed or mount ?** the error will happen as 
`Error: vendor/github.com/NVIDIA/go-nvml/pkg/dl/dl.go:34:18: could not determine kind of name for C.RTLD_DEEPBIND`

as 

https://github.com/sustainable-computing-io/kepler/actions/runs/3361335455/jobs/5571601524#step:4:53

as 

https://github.com/NVIDIA/go-nvml/blob/main/pkg/dl/dl.go#L25

need NVIDIA C library

**Comment by SamYuan1990** [comment]
@marceloamaral , 
https://github.com/sustainable-computing-io/kepler/pull/347#issuecomment-1297090880
is the explain for why there is a c library issue on mac as you found.

https://github.com/sustainable-computing-io/kepler/pull/347#issuecomment-1297082575
is a general question as how should we handle this c library missing case.
in my point of view, we should follow build tags.

it's also been found at https://github.com/sustainable-computing-io/kepler/issues/184#issuecomment-1249013531

**Review by SamYuan1990 — CHANGES_REQUESTED** [review]
please think twice before merge.

as we have different build tag.
macOS Unit test plays role of no bcc, no GPU unit test.
and bcc unit test with container plays role of bcc and GPU build tag unit test.

do we force relays on BCC and GPU otherwise make kepler may `panic` is acceptable?

**Comment by marceloamaral** [comment]
@SamYuan1990 converted to draft to investigate it more

**Comment by marceloamaral** [comment]
Closing this PR because the macOS use case is important to show the support of cross-building.

```
Some systems have compatibility issues with the nvidia library. 
See https://github.com/sustainable-computing-io/kepler/issues/184
Therefore, we can disable files that use the NVIDIA library using the "+build gpu" tag. 
This means that the compiler will only include these files if the compilation has the gpu tag.
```

**Pull request closed without merging**
