### PR TITLE
Revert "Add GH workflow for fornightly release on every 1&3 Friday at 09:30 hrs"

### PR DESCRIPTION
**Pull request by husky-parul**
Reverts sustainable-computing-io/kepler#757

@SamYuan1990 @rootfs reverting this PR

### CODE REVIEW

**Review by SamYuan1990 — APPROVED** [review]
LGTM

**Comment by SamYuan1990** [comment]
we can have a discuss with release management for this issue.

**Comment by husky-parul** [comment]
@rootfs keeping this open until the discussion is complete.
cc @SamYuan1990

**Comment by SamYuan1990** [comment]
https://github.com/sustainable-computing-io/kepler/actions/runs/5484970053/jobs/9993183240
as the CI fails, we have two options, 
- merge this PR and remake the pipeline.
- use this PR to enhancement and fix the job.
@husky-parul , @rootfs wdyt?

**Comment by rootfs** [comment]
odd, why the tag is recreated?

**Comment by SamYuan1990** [comment]
Merge this PR and close for night release pipeline fails.

**Pull request merged**
