### PR TITLE
chore(validator): refactor prometheus initialization

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR makes below changes to:
* prometheus/__init__.py:
  * Removes duplicate imports
  * Use list comprehensions for better readability
  * Simplify the acquisition of common timestamps
  * Ensure proper typing for function arguments and return types
  * Use NumPy operations directly within the metric calculation functions
  * Format the code using Black
* prometheus/test_prometheus.py
  * Format the code using Black
  * Minor update to existing test

### CODE REVIEW

**Comment by vprashar2929** [comment]
cc: @sthaha @KaiyiLiu1234

**Comment by rootfs** [comment]
@vprashar2929 can you rebase this?

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@sthaha @KaiyiLiu1234 any final comment on this one?

**Comment by vprashar2929** [comment]
@rootfs I will close this PR as #1527 addresses all the changes

**Pull request closed without merging**
