### PR TITLE
ebpf: track process cpu time at tgid level on all CPUs

### PR DESCRIPTION
**Pull request by rootfs**
this fix is to track processes on-cpu time, this is inspired by the usage in [this](https://github.com/iovisor/bcc/blob/master/tools/cpudist.py) bcc tool

### CODE REVIEW

**Comment by rootfs** [comment]
# without the fix, most container cpu time are zero

```console
# curl localhost:8888/metrics |grep kepler |grep kepler_container_bpf_cpu_time_us_total| sort -k 2 -g |tail -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  389k    0  389k    0     0  34.6M      0 --:--:-- --:--:-- --:--:-- 34.6M
kepler_container_bpf_cpu_time_us_total{container_id="9280edfcd4e0f83744753ca186c91b3c17d5600394ec1fa4d3c5e2f5473112c9",container_name="kube-rbac-proxy-main",container_namespace="monitoring",pod_name="kube-state-metrics-5cfdc9d86d-8rs7m"} 0
kepler_container_bpf_cpu_time_us_total{container_id="94720e86be011912b0c9d43eba0589e6f17eba8fd71d599b43412f24614212ab",container_name="kepler-exporter",container_namespace="kepler",pod_name="kepler-exporter-jt8jb"} 0
kepler_container_bpf_cpu_time_us_total{container_id="afcaf8bc29804bbab81b7b9c8382402cc170b1539633f7331d80af397b4ea10d",container_name="kube-proxy",container_namespace="kube-system",pod_name="kube-proxy-s8pjz"} 0
kepler_container_bpf_cpu_time_us_total{container_id="ba64701614e16e9f6388483fc49692102bd9f73f07fba6ddd3e9c77d40821d45",container_name="module-configmap-reloader",container_namespace="monitoring",pod_name="blackbox-exporter-67976fd754-j8tjs"} 0
kepler_container_bpf_cpu_time_us_total{container_id="d06bdca41af3ec439c68de7b69e82fcbe88e1cf8bf369d73ce9dbc1b833bdc6e",container_name="cuda-vector-add",container_namespace="default",pod_name="gpu-test"} 0
kepler_container_bpf_cpu_time_us_total{container_id="d74c1ffb00a17ca0578af0dd425e6965ae582e07e336ce49fd7fc29f03bdf770",container_name="install-cni",container_namespace="kube-flannel",pod_name="kube-flannel-ds-xqnmb"} 0
kepler_container_bpf_cpu_time_us_total{container_id="dc5790f2d1067def7555cb4b9c1da06aa19000f2e603050d36ed8f882b20c5ae",container_name="kube-rbac-proxy-self",container_namespace="monitoring",pod_name="kube-state-metrics-5cfdc9d86d-8rs7m"} 0
kepler_container_bpf_cpu_time_us_total{container_id="df7205bc257af8046d4b0c7a5602c4d6686f8084941a1f290ca6973ffda8bd4b",container_name="config-reloader",container_namespace="monitoring",pod_name="prometheus-k8s-0"} 0
kepler_container_bpf_cpu_time_us_total{container_id="142dff6c273f8e4553031270221ee30176e3e4bce767e6831e88f1150513ec8f",container_name="grafana",container_namespace="monitoring",pod_name="grafana-65877b76c7-jhwq7"} 5
```


# with this fix, the cpu metrics makes sense
```console
# curl localhost:8888/metrics |grep kepler |grep kepler_container_bpf_cpu_time_us_total| sort -k 2 -g |tail -10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  531k    0  531k    0     0  37.0M      0 --:--:-- --:--:-- --:--:-- 37.0M
kepler_container_bpf_cpu_time_us_total{container_id="3db07badcc5d5cc1fc00f8018d1c874edec216bbea7e1c2aa6d0ca5eae9afacf",container_name="kube-controller-manager",container_namespace="kube-system",pod_name="kube-controller-manager-rhel"} 2
kepler_container_bpf_cpu_time_us_total{container_id="530622bdda4155b6359d3d3462171e90cd7eac336fd0665d5fae108a1054767a",container_name="prometheus-adapter",container_namespace="monitoring",pod_name="prometheus-adapter-867598997b-k5zvz"} 18
kepler_container_bpf_cpu_time_us_total{container_id="08879b372fef265b4015b4f2fd235fca49e9615ae8385091092a62448a1f5922",container_name="prometheus-adapter",container_namespace="monitoring",pod_name="prometheus-adapter-867598997b-k9n8d"} 22
kepler_container_bpf_cpu_time_us_total{container_id="7f45e09040062e77e9f10e52d365a00199dc1ce6a6eff2a71b60fbeb3a3b5944",container_name="node-exporter",container_namespace="monitoring",pod_name="node-exporter-27nsx"} 43
kepler_container_bpf_cpu_time_us_total{container_id="142dff6c273f8e4553031270221ee30176e3e4bce767e6831e88f1150513ec8f",container_name="grafana",container_namespace="monitoring",pod_name="grafana-65877b76c7-jhwq7"} 44
kepler_container_bpf_cpu_time_us_total{container_id="7b308816076f3131cf2c3cb22ba55dd75866570a92c1b0e45364ef32d7a0fce7",container_name="kube-apiserver",container_namespace="kube-system",pod_name="kube-apiserver-rhel"} 96
kepler_container_bpf_cpu_time_us_total{container_id="94720e86be011912b0c9d43eba0589e6f17eba8fd71d599b43412f24614212ab",container_name="kepler-exporter",container_namespace="kepler",pod_name="kepler-exporter-jt8jb"} 285
kepler_container_bpf_cpu_time_us_total{container_id="1540d3bf9ea8c34b8cf5f2049b27168c880d57a020a2e39727faf925076a1f63",container_name="prometheus",container_namespace="monitoring",pod_name="prometheus-k8s-1"} 533
kepler_container_bpf_cpu_time_us_total{container_id="47699e80078eb30218cd641a29958ac8acd6e1882ca9bb7a4b9effd21c5c416d",container_name="prometheus",container_namespace="monitoring",pod_name="prometheus-k8s-0"} 545
kepler_container_bpf_cpu_time_us_total{container_id="system_processes",container_name="system_processes",container_namespace="system",pod_name="system_processes"} 6156
```

**Comment by jichenjc** [comment]
@rootfs I knew @sunya-ch changed some build method so we are using CO-RE do I need to do any special handling for such ebpf code change? I download code and `make` the container but still seeing many 0 reported in log file ..

```
--
        CPUTime:  0 (0)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 0 (0)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:0 (0) cgroupfs_cpu_usage_us:0 (0) cgroupfs_ioread_bytes:0 (0) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]
--
        CPUTime:  0 (2)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 0 (6)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:1 (23) cgroupfs_cpu_usage_us:0 (108055998) cgroupfs_ioread_bytes:29663232 (682254336) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (229376) cgroupfs_memory_usage_bytes:0 (38187008) cgroupfs_system_cpu_usage_us:0 (29256903) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:0 (78799095)]
        CPUTime:  0 (8)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 0 (2)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:1 (28) cgroupfs_cpu_usage_us:0 (193072784) cgroupfs_ioread_bytes:130564096 (3655794688) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (180224) cgroupfs_memory_usage_bytes:0 (42131456) cgroupfs_system_cpu_usage_us:0 (105916392) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:0 (87156391)]
--
        CPUTime:  0 (11)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 13 (20)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:1 (28) cgroupfs_cpu_usage_us:4175 (318574241) cgroupfs_ioread_bytes:90869760 (2544353280) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (229376) cgroupfs_memory_usage_bytes:0 (57380864) cgroupfs_system_cpu_usage_us:1614 (80574400) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:2562 (237999841)]
--
        CPUTime:  0 (10)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 0 (6)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:1 (27) cgroupfs_cpu_usage_us:0 (163806241) cgroupfs_ioread_bytes:577536 (15593472) cgroupfs_iowrite_bytes:508723200 (13734850560) cgroupfs_kernel_memory_usage_bytes:0 (196608) cgroupfs_memory_usage_bytes:0 (22843392) cgroupfs_system_cpu_usage_us:0 (56059135) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (107747105)]
--
        CPUTime:  0 (0)
        NetTX IRQ: 0 (0)
        NetRX IRQ: 0 (0)
        Block IRQ: 0 (0)
        counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
        cgroupfs: map[block_devices_used:0 (0) cgroupfs_cpu_usage_us:0 (0) cgroupfs_ioread_bytes:0 (0) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]

```

**Comment by sunya-ch** [comment]
> @rootfs I knew @sunya-ch changed some build method so we are using CO-RE do I need to do any special handling for such ebpf code change? I download code and `make` the container but still seeing many 0 reported in log file ..
> 
> cat output | grep -A 5 'CPUTime: 0'
> 
> ```
> --
>         CPUTime:  0 (0)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 0 (0)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:0 (0) cgroupfs_cpu_usage_us:0 (0) cgroupfs_ioread_bytes:0 (0) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]
> --
>         CPUTime:  0 (2)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 0 (6)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:1 (23) cgroupfs_cpu_usage_us:0 (108055998) cgroupfs_ioread_bytes:29663232 (682254336) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (229376) cgroupfs_memory_usage_bytes:0 (38187008) cgroupfs_system_cpu_usage_us:0 (29256903) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:0 (78799095)]
>         CPUTime:  0 (8)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 0 (2)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:1 (28) cgroupfs_cpu_usage_us:0 (193072784) cgroupfs_ioread_bytes:130564096 (3655794688) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (180224) cgroupfs_memory_usage_bytes:0 (42131456) cgroupfs_system_cpu_usage_us:0 (105916392) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:0 (87156391)]
> --
>         CPUTime:  0 (11)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 13 (20)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:1 (28) cgroupfs_cpu_usage_us:4175 (318574241) cgroupfs_ioread_bytes:90869760 (2544353280) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (229376) cgroupfs_memory_usage_bytes:0 (57380864) cgroupfs_system_cpu_usage_us:1614 (80574400) cgroupfs_tcp_memory_usage_bytes:0 (4096) cgroupfs_user_cpu_usage_us:2562 (237999841)]
> --
>         CPUTime:  0 (10)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 0 (6)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:1 (27) cgroupfs_cpu_usage_us:0 (163806241) cgroupfs_ioread_bytes:577536 (15593472) cgroupfs_iowrite_bytes:508723200 (13734850560) cgroupfs_kernel_memory_usage_bytes:0 (196608) cgroupfs_memory_usage_bytes:0 (22843392) cgroupfs_system_cpu_usage_us:0 (56059135) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (107747105)]
> --
>         CPUTime:  0 (0)
>         NetTX IRQ: 0 (0)
>         NetRX IRQ: 0 (0)
>         Block IRQ: 0 (0)
>         counters: map[cache_miss:0 (0) cpu_cycles:0 (0) cpu_instr:0 (0) cpu_ref_cycles:0 (0)]
>         cgroupfs: map[block_devices_used:0 (0) cgroupfs_cpu_usage_us:0 (0) cgroupfs_ioread_bytes:0 (0) cgroupfs_iowrite_bytes:0 (0) cgroupfs_kernel_memory_usage_bytes:0 (0) cgroupfs_memory_usage_bytes:0 (0) cgroupfs_system_cpu_usage_us:0 (0) cgroupfs_tcp_memory_usage_bytes:0 (0) cgroupfs_user_cpu_usage_us:0 (0)]
> ```

I think this will be helpful for bcc build. I made libbpf as an alternative. I think it is safer to keep the default one to bcc until we tested libbpf on all environments that currently working with bcc.

**Comment by rootfs** [comment]
@sunya-ch @jichenjc can you review this PR?

**Pull request merged**
