### PR TITLE
fix: switch from dummy to estimated method

### PR DESCRIPTION
**Pull request by jichenjc**
estimate need files 

"/var/lib/kepler/data/normalized_cpu_arch.csv"   ==> from docker file 
"/var/lib/kepler/data/power_data.csv" ==> from docker file 
"/proc/meminfo" ==> host level, same to other /proc usage in kepler

### CODE REVIEW

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@jichenjc looks good. Now we don't need [kepler/data](https://github.com/sustainable-computing-io/kepler/tree/main/data) and [their container image copy](https://github.com/sustainable-computing-io/kepler/blob/main/build/Dockerfile#L36-L39), can you remove them too?

**Comment by rootfs** [comment]
@jichenjc please also remove https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/components/source/estimate.go

**Comment by jichenjc** [comment]
>>>@jichenjc please move [GetCPUArchitecture](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/components/source/estimate.go#L62) from [estimate.go](https://github.com/sustainable-computing-io/kepler/blob/main/pkg/power/components/source/estimate.go) and remove the rest of the file.

um... I switch from dummy to estimated .. then why remove this file? maybe I misunderstand your comment?

**Comment by rootfs** [comment]
the estimate method is not used any more, can you follow up with a new PR to remove this method? Thanks.

**Pull request merged**
