### PR TITLE
CI: fix go get error

### PR DESCRIPTION
**Pull request by SamYuan1990**
reference to latest CI error, update `go get -u` to `go get -d`

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@marceloamaral https://github.com/sustainable-computing-io/kepler/actions/runs/3416088845/jobs/5685876157
will `make cluster sync` seems not cover `make` ?

here is post action with error
https://github.com/sustainable-computing-io/kepler/blob/main/.github/workflows/image.yml#L20

here is pull action with success
https://github.com/sustainable-computing-io/kepler/blob/main/.github/workflows/integration_test.yml#L29

**Comment by SamYuan1990** [comment]
test make locally
```
yuanyi@yuanyideMacBook-Pro kepler % make
/Applications/Xcode.app/Contents/Developer/usr/bin/make _build_containerized ARCH=amd64
go get -d github.com/go-bindata/go-bindata/...
go: added github.com/go-bindata/go-bindata v3.1.2+incompatible
./hack/bindata.sh
go mod tidy
go mod vendor
gofmt -e -d -s -l -w pkg/ cmd/
echo BIN_TIMESTAMP==2022-11-08T14:26:56Z
BIN_TIMESTAMP==2022-11-08T14:26:56Z
/usr/local/bin/docker build -t quay.io/sustainable_computing_io/kepler:v0.3-103-g37205be-linux-amd64 \
                -f "/Users/yuanyi/go/src/github.com/SamYuan1990/kepler"/build/Dockerfile \
                --build-arg SOURCE_GIT_TAG=v0.3-103-g37205be \
                --build-arg BIN_TIMESTAMP=2022-11-08T14:26:56Z \
                --build-arg ARCH=amd64 \
                --build-arg MAKE_TARGET="cross-build-linux-amd64" \
                --platform="linux/amd64" \
```

**Comment by rootfs** [comment]
per [doc](https://go.dev/doc/go-get-install-deprecation), this fix looks good to me

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@SamYuan1990 can you check if the CI uses golang 1.18+?

**Comment by rootfs** [comment]
CI failed during merge
```
go get -d github.com/go-bindata/go-bindata/...
go: downloading github.com/go-bindata/go-bindata v3.1.2+incompatible
go get: added github.com/go-bindata/go-bindata v3.1.2+incompatible
./hack/bindata.sh
./hack/bindata.sh: 5: /home/runner/go/bin/go-bindata: not found
go mod tidy
go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
make[1]: *** [Makefile:63: tidy-vendor] Error 1
make[1]: Leaving directory '/home/runner/work/kepler/kepler'
make: *** [Makefile:100: build-containerized-cross-build-linux-amd64] Error 2
```

**Comment by SamYuan1990** [comment]
> CI failed during merge
> 
> ```
> go get -d github.com/go-bindata/go-bindata/...
> go: downloading github.com/go-bindata/go-bindata v3.1.2+incompatible
> go get: added github.com/go-bindata/go-bindata v3.1.2+incompatible
> ./hack/bindata.sh
> ./hack/bindata.sh: 5: /home/runner/go/bin/go-bindata: not found
> go mod tidy
> go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
> make[1]: *** [Makefile:63: tidy-vendor] Error 1
> make[1]: Leaving directory '/home/runner/work/kepler/kepler'
> make: *** [Makefile:100: build-containerized-cross-build-linux-amd64] Error 2
> ```

a ha, https://github.com/sustainable-computing-io/kepler/actions/runs/3420731403/jobs/5695929499#step:3:5
the image CI is still go 1.17

**Comment by SamYuan1990** [comment]
> CI failed during merge
> 
> ```
> go get -d github.com/go-bindata/go-bindata/...
> go: downloading github.com/go-bindata/go-bindata v3.1.2+incompatible
> go get: added github.com/go-bindata/go-bindata v3.1.2+incompatible
> ./hack/bindata.sh
> ./hack/bindata.sh: 5: /home/runner/go/bin/go-bindata: not found
> go mod tidy
> go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
> make[1]: *** [Makefile:63: tidy-vendor] Error 1
> make[1]: Leaving directory '/home/runner/work/kepler/kepler'
> make: *** [Makefile:100: build-containerized-cross-build-linux-amd64] Error 2
> ```

fix at https://github.com/sustainable-computing-io/kepler/pull/372

**Pull request merged**
