### PR TITLE
Refactor: move bcc to bpf package

### PR DESCRIPTION
**Pull request by SamYuan1990**
As a part of #320 , refactor from bcc to bpf package

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Review by marceloamaral — CHANGES_REQUESTED** [review]
Looks good! Thanks!

Can you solve the conflicts?

**Comment by marceloamaral** [comment]
Thanks @SamYuan1990 

What about the `bpfassets` folder which is outside the `pkg` folder? It contains the `.c` code...

Also you need to update the `scripts/bindata.sh` file.
Btw, the `scripts/bindata.sh` should be moved to the `hack/` folder.
Also, `scripts/bindata.sh` (`hack/bindata.sh`) must always be called before any build process. We are missing this....
Then it will also be good to update the Makefile...

**Comment by marceloamaral** [comment]
You can update the Makefile in another PR...

But you should update the `scripts/bindata.sh` and move the `bpfassets` in this PR...

**Comment by SamYuan1990** [comment]
> Thanks @SamYuan1990
> 
> What about the `bpfassets` folder which is outside the `pkg` folder? It contains the `.c` code...

in this pr, I would like to follow #320  structure, so it's in `pkg` folder for now.

> Also you need to update the `scripts/bindata.sh` file. Btw, the `scripts/bindata.sh` should be moved to the `hack/` folder. Also, `scripts/bindata.sh` (`hack/bindata.sh`) must always be called before any build process. We are missing this.... Then it will also be good to update the Makefile...

when should the `bindata.sh` been invoked? I didn't found in current code.

**Comment by SamYuan1990** [comment]
btw, I even want to remove the bcc related code as https://github.com/sustainable-computing-io/kepler/discussions/323

**Comment by rootfs** [comment]
@SamYuan1990 The bpf asset can go to its own pkg following the process by @marceloamaral 
`bpf_perf.go` is the helper function used by attacher, it should stay as the the attacher

**Comment by SamYuan1990** [comment]
> @SamYuan1990 The bpf asset can go to its own pkg following the process by @marceloamaral `bpf_perf.go` is the helper function used by attacher, it should stay as the the attacher

```
.
├── bpf **(move all bpf related files to here)**
│   ├── assets.go
│   └── perf_event_bindata.go
│   └── perf_event.c
│   ├── attacher
│   │   ├── bcc_attacher.go
│   │   ├── bcc_attacher_stub.go
│   │   ├── bpf_perf.go
```
@rootfs , I suppose we'd better working on the same page?
as ref to above tree structure from @marceloamaral in #320 , the attacher is under bpf?

**Comment by rootfs** [comment]
add an `bpfasset` under `bpf` and make all the bpf asset into that pkg. The attacher pkg looks good.

**Comment by SamYuan1990** [comment]
@marceloamaral , I just adjust `scripts/bindata.sh` let's see anything other changes is need for this PR.

**Comment by marceloamaral** [comment]
@SamYuan1990 could you please fix the conflicts?

**Comment by SamYuan1990** [comment]
> @SamYuan1990 could you please fix the conflicts?

done

**Review by marceloamaral — APPROVED** [review]
/lgtm

**Pull request merged**
