### PR TITLE
CI: test case enhancement for e2e metric

### PR DESCRIPTION
**Pull request by SamYuan1990**
Following https://github.com/prometheus/prometheus/blob/main/model/textparse/promparse_test.go as prometheus handler.
Following https://onsi.github.io/ginkgo/#table-specs refactor test case.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
related with #349

**Comment by SamYuan1990** [comment]
try to add bcc lib at host agent.

**Comment by rootfs** [comment]
looks good, let's see what the CI's decision

**Comment by SamYuan1990** [comment]
@rootfs , if I am right with those metrics, all of them should larger than 0 once bcc lib there? and could you please clarify how cgroup version works?

**Comment by rootfs** [comment]
the current offline metrics based model uses cgroup v2 stats, that's why we check the kepler metrics only when cgroup is v2.

**Comment by SamYuan1990** [comment]
> the current offline metrics based model uses cgroup v2 stats, that's why we check the kepler metrics only when cgroup is v2.

but if fact, those metrics are there... no matter cgroup v2 or not. for example, even if we disabled gpu there for CI. `kepler_container_gpu_joules_total` still appears.

**Comment by SamYuan1990** [comment]
> the current offline metrics based model uses cgroup v2 stats, that's why we check the kepler metrics only when cgroup is v2.

so which means, cgroup version has no impact with metrics appears or not, but just impacts the value?

**Comment by SamYuan1990** [comment]
> the current offline metrics based model uses cgroup v2 stats, that's why we check the kepler metrics only when cgroup is v2.

by leaving value check works as todo item in another pr make this pr ready for review.

**Review by rootfs — APPROVED** [review]

**Pull request merged**
