### PR TITLE
Fix missing processes issue

### PR DESCRIPTION
**Pull request by marceloamaral**
This PR fixes the issue #844

The changes include:

- [x] fix libbpf get batch premature return bug to collect all keys in the map
- [x] fix libbpf code to use current task to set the right cgroup id
- [x] increase the bpf map size to be able to trace more threads
- [x] fix get containerID from cgroup path bug of return containerID unknown
- [x] fix get containerID intermittently returning system_processes instead of the real containerID
- [x] fix containerID bug to return a valid container ID, some system processes were not having the system_processes ID, so that the aggregations were not properly done
- [x] reset PIDs list since it changes in each metric collection
- [x] update to use a valid PID to start a cgroup manager

### CODE REVIEW

**Comment by marceloamaral** [comment]
example of previous invalid container ID:
```
I0817 10:39:05.777237       1 resolve_container.go:264] ##### DEBUG: extractPodContainerIDfromPath 2 containerID: /sys/fs/cgroup/system.slice/containerd.service cgroup path: /sys/fs/cgroup/system.slice/containerd.service
```

**Comment by marceloamaral** [comment]
@sunya-ch @SamYuan1990 the libbpf building is failing in the integration test.
Do you know how to fix it?

**Comment by rootfs** [comment]
@marceloamaral do you have a updated https://github.com/sustainable-computing-io/kepler/tree/main/bpfassets/libbpf/bpf.o

**Comment by marceloamaral** [comment]
@rootfs updated!

**Review by rootfs — APPROVED** [review]

**Pull request merged**
