### PR TITLE
CI: enable commit msg check

### PR DESCRIPTION
**Pull request by SamYuan1990**
this pr use https://github.com/GsActions/commit-message-checker with regex as implementation.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
resolve #253

**Comment by rootfs** [comment]
What are the magic format look like? Should the format be documented?

**Comment by SamYuan1990** [comment]
> What are the magic format look like? 

https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines
it's not any magic format, as it discussed in #253 , pre discussed with @marceloamaral before, we want to have some commit message check to ensure commit message is meaningful.

> Should the format be documented?
good idea.

**Comment by rootfs** [comment]
lgtm

@marceloamaral any feedback?

**Review by marceloamaral — APPROVED** [review]
Looks good!
/lgtm

> The first word in the commit message subject should be capitalized unless it starts with a lowercase symbol or other identifier

I was not aware of that :)

**Pull request merged**
