### PR TITLE
Revert "feat(kubernetes): Use workqueues"

### PR DESCRIPTION
**Pull request by vprashar2929**
This reverts commit b424607400784bc1971d872856d09ef6c7650ace.

### CODE REVIEW

**Comment by rootfs** [comment]
@maryamtahhan #1686

**Comment by rootfs** [comment]
@vprashar2929 can you sign DCO?
```
Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin revert-workqueue
```

**Comment by vprashar2929** [comment]
@rootfs I had a hunch that maybe the e2e failure issue might be introduced in the workqueues PR so just wanted to verify this on CI by reverting that particular patch

**Comment by dave-tucker** [comment]
Closing since #1686 has fixed the issue

**Pull request closed without merging**
