### PR TITLE
chore(readme): update architecture diagram

### PR DESCRIPTION
**Pull request by rootfs**
The diagram preview can be found [here](https://github.com/sustainable-computing-io/kepler/blob/50b1dd6e1f1c02da8444b3151f57ac635a1605eb/README.md)

### CODE REVIEW

**Comment by vimalk78** [comment]
@rootfs please update the diagram preview

**Comment by vimalk78** [comment]
[preview ](https://github.com/sustainable-computing-io/kepler/blob/dd9938eb98dd84fb62b15b0ae4d9418f161b0bf7/README.md)

**Comment by rootfs** [comment]
@vimalk78 updated, can you check again? thanks

https://github.com/sustainable-computing-io/kepler/blob/609a3ff8d73ed25488b875d751d0f50096e1df86/README.md

**Review by vimalk78 — APPROVED** [review]

**Pull request merged**
