### PR TITLE
CI:Post Action clean up for lint, fmt, image build and push, unit test

### PR DESCRIPTION
**Pull request by SamYuan1990**
Post Action clean up for 
- lint, remove from post action.
- fmt, remove from post action.
- image build and push, remove from post action, integrated with integration test, now push after integration passed.
- unit test, remove bcc path from post action.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
resolve #222

**Comment by rootfs** [comment]
@SamYuan1990 looks cool!

one more thing, can you set go coverage to push too?
image

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
the post merge phase still runs unit test
image

**Comment by SamYuan1990** [comment]
> the post merge phase still runs unit test image

from debugging,
https://github.com/sustainable-computing-io/kepler/actions/runs/3098974788/jobs/5017636788#step:8:1 the test coverage is no change... so it's skipped.:-)

**Pull request merged**
