### PR TITLE
 avoid set CONTAINER_COMPONENTS_INIT_URL by default

### LINKED ISSUE #743: LR Model (DynComponentModelWeight):
**Is your feature request related to a problem? Please describe.**
Debug with Huamin  because the metrics are nulls and the kepler model server is not applicated.
We are on airgapped environment and we need to have model kepler on an image because we've this error:

 model.go:87] Model Config CONTAINER_COMPONENTS: {UseEstimatorSidecar:false SelectedModel: SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json}
I0620 13:32:38.242168       1 lr.go:164] LR Model (DynComponentModelWeight): loadWeightFromURLorLocal(https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json): <nil>
lr.go:173] LR Model (DynComponentModelWeight): connection error: Get "https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json": dial tcp: lookup raw.githubusercontent.com on 172.30.0.10:53: no such host (https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json)

**Describe the solution you'd like**
I want to have metrics not null .

### PR DESCRIPTION
**Pull request by jichenjc**
Fixes #743

### CODE REVIEW

**Review by marceloamaral — APPROVED** [review]
/lgtm

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@jichenjc can you try the suggestion from @sunya-ch

**Review by sunya-ch — APPROVED** [review]
/lgtm

**Comment by sunya-ch** [comment]
> The source of the problem seems to be something else:
> [#743 (comment)](https://github.com/sustainable-computing-io/kepler/issues/743#issuecomment-1600051486)

Agree. I think the problem is that the pod may not have network reachability to load the file as I also saw in some cluster before.

**Review by marceloamaral — APPROVED** [review]
/lgtm

**Comment by rootfs** [comment]
@jichenjc can you document this in kepler-doc? thanks

**Comment by jichenjc** [comment]
>>>@jichenjc can you document this in kepler-doc? thanks

sure, will do

**Pull request merged**
