### PR TITLE
Update perf err (or it will print nil always)

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by rootfs** [comment]
can linter capture this type of error?

**Comment by jichenjc** [comment]
check https://github.com/sustainable-computing-io/kepler/pull/213/files#diff-9460a34504f0c66b69c7bd5890c338e717e9abcc29d33dad961bd31d0edaf9bbL71

err is defined ,the reason is perfErr actually has more userful info and err is always nil from context

**Comment by rootfs** [comment]
@jichenjc can you see if [go static checker](https://staticcheck.io/) can detect mistakes like this?

**Comment by jichenjc** [comment]
not sure. .. @rootfs 
need some analysis later on , thanks for the link

**Pull request merged**
