### PR TITLE
remove: remove CPURefCycleLabel as it's not used, no need to collect

### PR DESCRIPTION
**Pull request by jichenjc**
related to https://github.com/sustainable-computing-io/kepler/issues/560

### CODE REVIEW

**Comment by marceloamaral** [comment]
CPURefCycle is used to calculate the CPU frequency.

**Review by marceloamaral — CHANGES_REQUESTED** [review]
CPURefCycle is used to calculate the CPU frequency.

@rootfs unless if we want to remove the CPU frequency we should keep this metric.

**Comment by rootfs** [comment]
@marceloamaral we need to keep the cpu frequency metrics. @jichenjc finds no reference of `CPURefCycle` in calculating CPU frequency. @marceloamaral can you double check?

**Comment by jichenjc** [comment]
there is CPUFreq https://github.com/sustainable-computing-io/kepler/blob/main/pkg/bpfassets/attacher/bcc_attacher.go#L129
I think it's not realated to the Refcycle (at least didn't find usage in the code) ..

**Comment by marceloamaral** [comment]
The calculation is done in the bpf code, please see [here](https://github.com/sustainable-computing-io/kepler/blob/main/bpfassets/perf_event/perf_event.c#L181).

The bpf code needs to have access to the hardware counter `CPURefCycle`.

**Comment by jichenjc** [comment]
yes, but https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/container_hc_collector.go#L38
didn't use it at all ..
and not handling here as well
https://github.com/sustainable-computing-io/kepler/blob/main/pkg/collector/container_hc_collector.go#L107

**Comment by marceloamaral** [comment]
@jichenjc yes, because we do not use this metric in the `userspace` (golang code).

The `CPURefCycle` is only necessary in the ebpf code and we cannot disable it if we need to calculate the CPU frequency.

Note that, the code that this PR is trying to remove enables ebpf to collect the `CPURefCycle`. Without this code, this metrics cannot be collect and then the CPU frequency cannot be calculated.

**Comment by jichenjc** [comment]
ok, thanks for the clarification , learn something :)

**Pull request closed without merging**
