### PR TITLE
fix: enhance sed command for uncomment operation in manifest script

### PR DESCRIPTION
**Pull request by vprashar2929**
This PR refines the `sed` command in the `hack/build-manifest.sh` script

### CODE REVIEW

**Comment by vprashar2929** [comment]
Downstream CI jobs that make use of `make build-manifest OPTS="OPENSHIFT_DEPLOY"` used to fail because the sed command was not able to uncomment properly. I verified this against OpenShift and it works

**Review by sthaha — CHANGES_REQUESTED** [review]
@vprashar2929 it would be easier to review if the pr explained what specific issue this fixes. 
E.g. the `sed` fails for `xyz` pattern.

**Comment by vprashar2929** [comment]
in the case of `make build-manifest OPTS="OPENSHIFT_DEPLOY"` the script tries to [uncomment openshift_scc](https://github.com/sustainable-computing-io/kepler/blob/8f0efb0aa256c8bea57d60a1bbad8e45721c3c13/manifests/k8s/config/exporter/kustomization.yaml#L3) resource. Since post [yamllint PR](https://github.com/sustainable-computing-io/kepler/commit/a621eaa73e0b0ba5599f9ad53393214f0d6e88a5#diff-ce1675478b4c8c479d6e136156c9e7f8108590d4d59850ab7b2b725f3a5f911aR3) the positioning of `- openshift_scc.yaml` got changed. The current sed command was unable to uncomment properly leading to final deployment.yaml without scc defined

**Comment by sthaha** [comment]
@vprashar2929 Could you please try 
```
diff --git a/manifests/k8s/config/exporter/kustomization.yaml b/manifests/k8s/config/exporter/kustomization.yaml
index 55514604d0d3..eebc200d5137 100644
--- a/manifests/k8s/config/exporter/kustomization.yaml
+++ b/manifests/k8s/config/exporter/kustomization.yaml
@@ -1,6 +1,6 @@
 resources:
   # uncomment this line for openshift
-  # - openshift_scc.yaml
+#  - openshift_scc.yaml
   - exporter.yaml
 #  uncomment this line if prometheus deployed
 #  - prometheus_common_service_monitor.yaml

```

**Comment by vprashar2929** [comment]
> @vprashar2929 Could you please try
> 
> ```
> diff --git a/manifests/k8s/config/exporter/kustomization.yaml b/manifests/k8s/config/exporter/kustomization.yaml
> index 55514604d0d3..eebc200d5137 100644
> --- a/manifests/k8s/config/exporter/kustomization.yaml
> +++ b/manifests/k8s/config/exporter/kustomization.yaml
> @@ -1,6 +1,6 @@
>  resources:
>    # uncomment this line for openshift
> -  # - openshift_scc.yaml
> +#  - openshift_scc.yaml
>    - exporter.yaml
>  #  uncomment this line if prometheus deployed
>  #  - prometheus_common_service_monitor.yaml
> ```

yamllint won't be happy with that 😄

**Pull request closed without merging**
