### PR TITLE
CI/CD Pipeline enhancement and tag

### PR DESCRIPTION
**Pull request by SamYuan1990**
related with https://github.com/sustainable-computing-io/kepler/pull/711
https://github.com/orgs/sustainable-computing-io/projects/2?pane=issue&itemId=28750581

### CODE REVIEW

**Comment by SamYuan1990** [comment]
Hi @jiere , @bradmccoydev, WDYT(what do you think)?

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
Anything OpenSSF guideline can help here too?

**Comment by marceloamaral** [comment]
Can you just add in the document that we might follow openSSF in the future?
Maybe also describe what is missing right now?

**Comment by SamYuan1990** [comment]
> Anything OpenSSF guideline can help here too?

But in this rfc, I still plan to use tag. or something may aline with OpenSSF.

**Comment by SamYuan1990** [comment]
> Can you just add in the document that we might follow openSSF in the future? Maybe also describe what is missing right now?

Again, which part of openSSF? @marceloamaral if you mean https://bestpractices.coreinfrastructure.org/en/login or SBOM(#685) or ?

**Pull request merged**
