### PR TITLE
testing: enable cpu profiling

### PR DESCRIPTION
**Pull request by rootfs**
will use this to investigate performance and scalability issues

### CODE REVIEW

**Comment by rootfs** [comment]
usage:
```bash
kepler -cpuprofile=cpu.prof
```
After getting enough workload, ctrl-c to stop it, then
```bash
go tool pprof cpu.prof
```

Sample output:
```console 
File: kepler
Build ID: d493096ef0923594df9c72ac35fa3c7f159248e4
Type: cpu
Time: Nov 11, 2022 at 2:28pm (EST)
Duration: 6.50s, Total samples = 2.31s (35.52%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 10
Showing nodes accounting for 1.88s, 81.39% of 2.31s total
Dropped 123 nodes (cum <= 0.01s)
Showing top 10 nodes out of 105
      flat  flat%   sum%        cum   cum%
     1.35s 58.44% 58.44%      1.35s 58.44%  runtime.cgocall
     0.25s 10.82% 69.26%      0.26s 11.26%  syscall.Syscall6
     0.07s  3.03% 72.29%      0.09s  3.90%  encoding/json.checkValid
     0.04s  1.73% 74.03%      0.04s  1.73%  runtime.pageIndexOf (inline)
     0.04s  1.73% 75.76%      0.14s  6.06%  runtime.scanobject
     0.03s  1.30% 77.06%      0.03s  1.30%  encoding/json.unquoteBytes
     0.03s  1.30% 78.35%      0.04s  1.73%  runtime.mapaccess2_faststr
     0.03s  1.30% 79.65%      0.03s  1.30%  syscall.Syscall
     0.02s  0.87% 80.52%      0.03s  1.30%  encoding/json.(*decodeState).rescanLiteral
     0.02s  0.87% 81.39%      0.03s  1.30%  encoding/json.(*decodeState).skip
```

**Comment by rootfs** [comment]
It looks gc takes quite some overhead:

```console
(pprof) top20 -cum (sync|runtime)
Active filters:
   focus=(sync|runtime)
Showing nodes accounting for 1400ms, 28.46% of 4920ms total
Dropped 122 nodes (cum <= 24.60ms)
Showing top 20 nodes out of 196
      flat  flat%   sum%        cum   cum%
    1330ms 27.03% 27.03%     1330ms 27.03%  runtime.cgocall
         0     0% 27.03%     1300ms 26.42%  github.com/iovisor/gobpf/bcc._Cfunc_bpf_module_create_c_from_string
         0     0% 27.03%     1300ms 26.42%  github.com/iovisor/gobpf/bcc.compile
         0     0% 27.03%     1300ms 26.42%  github.com/iovisor/gobpf/bcc.newModule
         0     0% 27.03%     1300ms 26.42%  github.com/iovisor/gobpf/bcc.newModule.func3
         0     0% 27.03%      800ms 16.26%  runtime.systemstack
         0     0% 27.03%      720ms 14.63%  github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Update
         0     0% 27.03%      720ms 14.63%  github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start.func1
         0     0% 27.03%      710ms 14.43%  github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateContainerResourceUsageMetrics
         0     0% 27.03%      660ms 13.41%  runtime.gcBgMarkWorker
         0     0% 27.03%      650ms 13.21%  github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateBPFMetrics
         0     0% 27.03%      620ms 12.60%  github.com/sustainable-computing-io/kepler/pkg/kubelet.(*KubeletPodLister).ListPods
         0     0% 27.03%      620ms 12.60%  runtime.gcBgMarkWorker.func2
      70ms  1.42% 28.46%      620ms 12.60%  runtime.gcDrain
         0     0% 28.46%      610ms 12.40%  github.com/sustainable-computing-io/kepler/pkg/cgroup.GetContainerID (inline)
         0     0% 28.46%      610ms 12.40%  github.com/sustainable-computing-io/kepler/pkg/cgroup.getContainerInfo
         0     0% 28.46%      610ms 12.40%  github.com/sustainable-computing-io/kepler/pkg/cgroup.updateListPodCache
         0     0% 28.46%      490ms  9.96%  encoding/json.(*decodeState).array
         0     0% 28.46%      490ms  9.96%  encoding/json.(*decodeState).object
         0     0% 28.46%      490ms  9.96%  encoding/json.(*decodeState).unmarshal
```

**Comment by rootfs** [comment]
for reference, I applied the profile patch to release-0.3 and this is the result:
```console
(pprof) top20 -cum (sync|runtime)
Active filters:
   focus=(sync|runtime)
Showing nodes accounting for 1360ms, 76.84% of 1770ms total
Showing top 20 nodes out of 96
      flat  flat%   sum%        cum   cum%
    1330ms 75.14% 75.14%     1330ms 75.14%  runtime.cgocall
         0     0% 75.14%     1320ms 74.58%  github.com/iovisor/gobpf/bcc._Cfunc_bpf_module_create_c_from_string
         0     0% 75.14%     1320ms 74.58%  github.com/iovisor/gobpf/bcc.compile
         0     0% 75.14%     1320ms 74.58%  github.com/iovisor/gobpf/bcc.newModule
         0     0% 75.14%     1320ms 74.58%  github.com/iovisor/gobpf/bcc.newModule.func3
         0     0% 75.14%       90ms  5.08%  github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).reader.func1
         0     0% 75.14%       60ms  3.39%  github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).readBPFEvent
         0     0% 75.14%       60ms  3.39%  runtime.gcBgMarkWorker
         0     0% 75.14%       60ms  3.39%  runtime.gcBgMarkWorker.func2
         0     0% 75.14%       60ms  3.39%  runtime.gcDrain
      30ms  1.69% 76.84%       60ms  3.39%  runtime.scanobject
         0     0% 76.84%       60ms  3.39%  runtime.systemstack
         0     0% 76.84%       50ms  2.82%  encoding/json.(*decodeState).array
         0     0% 76.84%       50ms  2.82%  encoding/json.(*decodeState).object
         0     0% 76.84%       50ms  2.82%  encoding/json.(*decodeState).unmarshal
         0     0% 76.84%       50ms  2.82%  encoding/json.(*decodeState).value
         0     0% 76.84%       50ms  2.82%  encoding/json.Unmarshal
         0     0% 76.84%       50ms  2.82%  github.com/sustainable-computing-io/kepler/pkg/podlister.(*KubeletPodLister).ListPods
         0     0% 76.84%       50ms  2.82%  github.com/sustainable-computing-io/kepler/pkg/podlister.GetPodName (inline)
         0     0% 76.84%       50ms  2.82%  github.com/sustainable-computing-io/kepler/pkg/podlister.getContainerInfo
(pprof) 
```

**Review by marceloamaral — APPROVED** [review]
This is awesome!
/lgtm

**Pull request merged**
