### PR TITLE
bot: sign off commit

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by rootfs** [comment]
this is to fix CI error due to signed commit requirement
```
Push to branch main
Pushing to https://github.com/sustainable-computing-io/kepler.git
POST git-receive-pack (4[9](https://github.com/sustainable-computing-io/kepler/actions/runs/3120435867/jobs/5061011691#step:9:10)5 bytes)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Commits must have valid signatures.
```

**Review by marceloamaral — APPROVED** [review]
/lgmt

**Comment by marceloamaral** [comment]
@rootfs it seems that you need to sign your commit ;)

**Comment by rootfs** [comment]
It looks `-s` is not sufficient for signed commits.

**Comment by marceloamaral** [comment]
>It looks -s is not sufficient for signed commits.

Humm, it should be....Probably there is a problem verifying the signed commits...

**Comment by rootfs** [comment]
@marceloamaral you are right, signed and sign off are different. Signed commits look quite a logistic challenge. I disabled it. For the purpose of DCO, let's use commit signoffs.

**Comment by rootfs** [comment]
image

**Pull request merged**
