### PR TITLE
multi-arch: build kepler multi-arch image (#203)

### PR DESCRIPTION
**Pull request by rootfs**
* multi-arch: build kepler multi-arch image

Signed-off-by: huoqifeng <huoqif@cn.ibm.com>

* Update image-kepler.yml

Signed-off-by: huoqifeng <huoqif@cn.ibm.com>
Co-authored-by: Huamin Chen <rootfs@users.noreply.github.com>

### CODE REVIEW

**Comment by rootfs** [comment]
@huoqifeng please review and let's merge it to the main branch

**Comment by huoqifeng** [comment]
@rootfs was the git actions passed?

**Comment by rootfs** [comment]
@huoqifeng no, it failed during build
```
docker build -t localhost:5001/kepler:01446d1-linux-amd64 \
	-f "/home/runner/work/kepler/kepler"/build/Dockerfile \
	--build-arg SOURCE_GIT_TAG=01446d1 \
	--build-arg BIN_TIMESTAMP=2023-01-09T14:46:09Z \
	--build-arg ARCH=amd64 \
	--build-arg MAKE_TARGET="cross-build-linux-amd64" \
	--platform="linux/amd64" \
	.
Sending build context to Docker daemon  185.2MB

Step 1/23 : ARG ARCH=$TARGETARCH
Step 2/23 : FROM --platform=$BUILDPLATFORM quay.io/sustainable_computing_io/kepler_builder:ubi-8.6-bcc-0.24-go1.18 as builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
make[1]: *** [Makefile:97: _build_containerized] Error 1
make[1]: Leaving directory '/home/runner/work/kepler/kepler'
make: *** [Makefile:219: cluster-sync] Error 2
```

**Comment by rootfs** [comment]
also link to s390x #543

**Comment by SamYuan1990** [comment]
I suppose if we want to add multi-arch support, we just need add parameters as we enable buildx via PR #572

**Comment by SamYuan1990** [comment]
close this for now as github agent fails with yum install.

**Pull request closed without merging**
