### PR TITLE
Add support for getting container id from cgroup path of different platforms

### PR DESCRIPTION
**Pull request by marceloamaral**
#### Why we need this PR:
Previous PR #138 has identified that different platforms might have different cgroup path.
Therefore, we need different regex to extract the container id from different cgroup paths.

My system has cgroup v1 and the OS is ubuntu, and after creating a kepler deployment, the cgroup path is as follows:
```
11:blkio:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod481c0ae9_7d40_46dd_b6ca_ba27cb64f87e.slice/docker-28a5e57257f81fcd6d592647dde27e06b53944d58af4fa546ad77a12ce8b41c2.scope
```

Another system, with RHEL and cgroup v1 has another path:
```
13:memory:/system.slice/containerd.service/kubepods-besteffort-pod0043435f_1854_4327_b76b_730f681a781d.slice:cri-containerd:01fd96f7ad292b02a8317cde4ecb8c7ef3cc06ffdd113f13410e0837eb2b2a20
```

#### What this PR does:
This PR adds the logic of another regex to extract the container id from cgroup path of different platforms

Signed-off-by: Marcelo Amaral <marcelo.amaral1@ibm.com>

### CODE REVIEW

**Comment by rootfs** [comment]
@ruomengh can you review this? thanks

**Review by ruomengh — APPROVED** [review]
LGTM

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
great teamwork!

**Comment by rootfs** [comment]
@marceloamaral @ruomengh @jichenjc would you like to write a unit test for these cases?

**Pull request merged**
