### PR TITLE
CI:impl for escapes detect as github action

### LINKED ISSUE #161: Add lint and memory leak detection as a basic test case in CI
**Is your feature request related to a problem? Please describe.**
Before unit test running, we'd better have a lint test and memory leak detection as a part of CI.

**Describe the solution you'd like**
`go fmt, vet, goimports ....`
```
go build -gcflags="-m -l" ./... | grep "escapes to heap" || true
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by SamYuan1990**
resolve #161 

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
https://github.com/sustainable-computing-io/kepler/actions/runs/3143019794/jobs/5107286079#step:4:398 @rootfs FYI

**Comment by SamYuan1990** [comment]
for vulnerability check https://github.com/sustainable-computing-io/kepler/actions/runs/3143172203/jobs/5107602033 as it is experimental tool, I didn't force it to pass for now.

**Comment by rootfs** [comment]
@sustainable-computing-io/kepler-testing

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
This is impressive!

**Comment by marceloamaral** [comment]
Looks very good! 

Are you planning to fix some of the issues? :)

/lgtm

**Comment by rootfs** [comment]
> https://github.com/sustainable-computing-io/kepler/actions/runs/3143019794/jobs/5107286079#step:4:398 @rootfs from this job we can know where do we have escapes.

this is really a tall list, any plan to fix them all or there are severity levels we can use to prioritize?

**Pull request merged**
