### PR TITLE
user podID instead of podName to avoid duplicate

### PR DESCRIPTION
**Pull request by jichenjc**
Fixes: #265 

Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

### CODE REVIEW

**Comment by marceloamaral** [comment]
While we were discussing using podID, I've created another PR (#287) that changes the logic to report metrics per container and not per pod...

When using containerID, we will not need to use podID....
I'm sorry you spend time working on this....

**Comment by jichenjc** [comment]
ok, not a big deal, your PR title ` Make Prometheus metrics conform with the Prometheus metrics guideline ` seems need update 

anyway, do we see use case that multiple container in one pod should be considered a bunch so that we should report energy about it ? otherwise, we can wait for your PR then close this

**Comment by marceloamaral** [comment]
I updated the title, thanks!

So I think we can simplify as much as possible and avoid duplication by just having the container metrics....

Pod metrics can be aggregated later in Prometheus with promQL, as is done for cpu, e.g., `container_cpu_usage_seconds_total`

**Review by rootfs — APPROVED** [review]

**Comment by marceloamaral** [comment]
@rootfs I think this PR was going to be close not merged....

**Comment by marceloamaral** [comment]
I am reverting this for now, but we can merge it again if needed

**Pull request merged**
