### PR TITLE
base image build refactoring

### PR DESCRIPTION
**Pull request by rootfs**
some refactoring, so we can use manual github action and bot credentials to build builder images.

### CODE REVIEW

**Comment by rootfs** [comment]
@vimalk78

**Review by vprashar2929 — APPROVED** [review]
LGTM

**Review by SamYuan1990 — COMMENTED** [review]
if so by this PR... the workflow will fail in daily job as the daily job reuse this PR by workflow call.

**Comment by SamYuan1990** [comment]
@rootfs , can we revert this PR as this PR blocks lots of things.
daily job https://github.com/sustainable-computing-io/kepler/actions/runs/8062349800
other PR https://github.com/sustainable-computing-io/kepler/actions/runs/8061230969

**Pull request merged**
