### PR TITLE
CI: use docker base bcc

### PR DESCRIPTION
**Pull request by SamYuan1990**
use docker based bcc instead of build bcc by us.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , there is no deb in `ghcr.io/iovisor/bcc:ubuntu-20.04` ... strange....

**Comment by rootfs** [comment]
@SamYuan1990 let's build the bcc deb in this repo https://github.com/sustainable-computing-io/kepler-ci-artifacts/

**Comment by rootfs** [comment]
The artifact is [here](https://github.com/sustainable-computing-io/kepler-ci-artifacts/actions/runs/3526947421)
```console
# gh api  -H "Accept: application/vnd.github+json" /repos/sustainable-computing-io/kepler-ci-artifacts/actions/artifacts/447363047/zip |zcat | tar xzvf -
bcc-lua_0.25.0-1_all.deb
bcc-tools_0.25.0-1_all.deb
libbcc-examples_0.25.0-1_amd64.deb
libbcc_0.25.0-1_amd64.deb
python-bcc_0.25.0-1_all.deb
python3-bcc_0.25.0-1_all.deb
```

**Comment by SamYuan1990** [comment]
> ```
> 447363047
> ```

what's this magic number?

**Comment by rootfs** [comment]
that is the artifact ID.

It looks the artificat are only valid for 90 days. Can you help to make the bcc pkg as a release pkg instead of build artifact?

**Pull request closed without merging**
