### PR TITLE
fix: nodeInfo => info

### PR DESCRIPTION
**Pull request by jichenjc**
https://sustainable-computing.io/design/metrics/#kepler-metrics-overview

```


    kepler_node_nodeInfo (Counter) This metric shows the node metada like the node CPU architecture.

    Note that this metrics is deprecated and might be updated to kepler_node_info in the next release.

```

### CODE REVIEW

**Comment by marceloamaral** [comment]
@sunya-ch does it affect the model server?

**Comment by sunya-ch** [comment]
It did affect but we can made a change to model server later.
/lgtm

**Comment by jichenjc** [comment]
thanks :)

**Comment by sunya-ch** [comment]
FYI: https://github.com/sustainable-computing-io/kepler-model-server/issues/105

**Review by marceloamaral — APPROVED** [review]

**Comment by marceloamaral** [comment]
@jichenjc, @SamYuan1990, and @rootfs,

I've noticed that the integration test is currently failing, and I suspect it might be due to this pull request (PR) here. You can review the specific failure details in the log provided at this link: https://github.com/sustainable-computing-io/kepler/actions/runs/5338323771/jobs/9675538716?pr=746.

The integration test is expecting the NodeInfo, we need to update it.

**Comment by rootfs** [comment]
@marceloamaral thank you for debugging this, yes, this makes sense now.

**Comment by jichenjc** [comment]
Thanks ~

I am curious why the issue is not reported early ,maybe the test added after this PR submitted? Anyway, thanks for the update @marceloamaral ~

**Pull request merged**
