### PR TITLE
GHA: release RPM

### PR DESCRIPTION
**Pull request by rootfs**
tested locally https://github.com/rootfs/kepler/actions/runs/4428285913/jobs/7767139632

The rpm artifact is available https://github.com/rootfs/kepler/releases/tag/v0.4.2

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , 1st please squash this pr... and do you have tried locally?

**Review by SamYuan1990 — CHANGES_REQUESTED** [review]
Squash please

**Comment by rootfs** [comment]
@SamYuan1990 the commits are squashed on merge

**Review by SamYuan1990 — APPROVED** [review]

**Pull request merged**
