### PR TITLE
enhance: build bpfdata in standalone build and add s390x support

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
related to https://github.com/sustainable-computing-io/kepler/issues/543

**Comment by SamYuan1990** [comment]
I think the major problem is about buildx support s390x in github action?

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@SamYuan1990 there is a rpm PR #540. The rpm will be built by ondemand or scheduled GHA (not there yet)

**Comment by jichenjc** [comment]
>>>I think the major problem for this PR is about buildx support s390x in github action?

this PR only provide a way to build locally
how to do this in github action is a follow up thing ..

**Pull request merged**
