### PR TITLE
multi-arch: build kepler multi-arch image

### PR DESCRIPTION
**Pull request by huoqifeng**
Use amd64 builder to build cross-platform kepler image. It depends on multi-arch `kepler_base` image.

Signed-off-by: huoqifeng <huoqif@cn.ibm.com>

### CODE REVIEW

**Comment by huoqifeng** [comment]
Depends in https://github.com/sustainable-computing-io/kepler/pull/202 and still WIP.

**Comment by huoqifeng** [comment]
@rootfs based on the flow here https://github.com/sustainable-computing-io/kepler/blob/main/.github/workflows/image-base.yml#L6, may you please create a branch `base` so that we can get a multi-arch `kepler_base` image built and pushed, so that this PR can be move ahead. maybe, may you please grant my access to branch `base` also, I can fix any problems found quickly...

**Comment by rootfs** [comment]
@huoqifeng here you go
image

**Comment by huoqifeng** [comment]
@rootfs Sorry, I was busy on other projects, hopefully, I can check it this weekend.

**Comment by rootfs** [comment]
@huoqifeng thanks! You don't have to get everything in this PR. If you can make your work in a good shape, I'll pick up where you have left and ping you for review later.

**Comment by huoqifeng** [comment]
@rootfs I think we need make sure https://github.com/sustainable-computing-io/kepler/blob/base/.github/workflows/image-base.yml work well as it will generate and push the base image, which is the base for multi-arch kepler images. I remembered I don't have permission to rebase and push the branch `base`. May you help grant my write access to this `base` branch?

**Comment by huoqifeng** [comment]
Lack of the permission to rebase branch `base` to `main`. anyone can help on that?

**Comment by SamYuan1990** [comment]
> Lack of the permission to rebase branch `base` to `main`. anyone can help on that?

changed the base branch from main to base.

**Comment by rootfs** [comment]
the integration test log is missing, do you happen to know what failed in the test? @huoqifeng

**Comment by huoqifeng** [comment]
I think we need make `base` branch get built successfully first, unfortunately I don't have permission to rebase the `base` branch.

**Comment by rootfs** [comment]
@huoqifeng let's pick up the change and see if the build works in the base branch.

**Pull request merged**
