### PR TITLE
Print model config after its change in kepler log

### PR DESCRIPTION
**Pull request by jiangphcn**
This PR is aimed to Address issue https://github.com/sustainable-computing-io/kepler-model-server/issues/141. The updated log is:

```
13 08:02:09.123144       1 model.go:120] Using Power Model AbsPower
I0913 08:02:09.123153       1 node_platform_energy.go:54] Using the LinearRegressor/AbsPower Power Model to estimate Node Platform Power
I0913 08:02:09.123167       1 model.go:176] Model Config NODE_COMPONENTS: {ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/WorkloadOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0913 08:02:09.123195       1 node_component_energy.go:43] The updated Model Config : &{ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/WorkloadOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used kubelet_cpu_usage kubelet_memory_bytes block_devices_used] SystemMetaDataFeatureNames:[cpu_architecture] SystemMetaDataFeatureValues:[Cascade Lake]}
I0913 08:02:09.222410       1 model.go:144] Using Power Model AbsPower
I0913 08:02:09.222447       1 node_component_energy.go:55] Using the EstimatorSidecar/AbsPower Power Model to estimate Node Component Power
I0913 08:02:09.222460       1 exporter.go:212] Initializing the GPU collector
I0913 08:02:15.227883       1 watcher.go:66] Using in cluster k8s config
```

Signed-off-by: Peng Hui Jiang <jiangph@cn.ibm.com>

### CODE REVIEW

**Review by rootfs — APPROVED** [review]

**Comment by sunya-ch** [comment]
@jiangphcn Thank you for the PR.
Basically, it is good as long as we can confirm the latest line of the log for the model config print.

However, it might be confused from the previous log print in https://github.com/sustainable-computing-io/kepler/blob/7ff90ba42bb89b1481c97391498f4fef3fde1ab8/pkg/model/model.go#L176.

At the same time, if we remove the log there, we need to add the log for container_total_energy and container_components_energy.

I would suggest to move the decision whether it is node level or not to model.go in the same way we do with getPowerModelOutputType and getPowerModelEnergySource.
We might add function isNodeLevel and return true for config.NodePlatformPowerKey and config.NodeComponentsPowerKey prefix and set it to modelConfig.IsNodePowerModel.

**Comment by jiangphcn** [comment]
```
root@node1:~# kc logs kepler-exporter-9qvhq -n kepler
Defaulted container "kepler-exporter" out of: kepler-exporter, estimator
I0918 03:04:42.231998       1 gpu.go:46] Failed to init nvml, err: could not init nvml: error opening libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0918 03:04:42.236549       1 qat.go:35] Failed to init qat-telemtry err: could not get qat status exit status 127
I0918 03:04:42.243547       1 exporter.go:158] Kepler running on version: v0.5.4-25-g47466bc-dirty
I0918 03:04:42.243577       1 config.go:270] using gCgroup ID in the BPF program: true
I0918 03:04:42.244115       1 config.go:272] kernel version: 5.15
I0918 03:04:42.244170       1 exporter.go:170] LibbpfBuilt: false, BccBuilt: true
I0918 03:04:42.244178       1 exporter.go:189] EnabledBPFBatchDelete: true
I0918 03:04:42.244212       1 rapl_msr_util.go:129] failed to open path /dev/cpu/0/msr: no such file or directory
I0918 03:04:42.244270       1 power.go:71] Unable to obtain power, use estimate method
I0918 03:04:42.244322       1 redfish.go:169] failed to get redfish credential file path
I0918 03:04:42.244349       1 power.go:56] use acpi to obtain power
I0918 03:04:42.244945       1 acpi.go:67] Could not find any ACPI power meter path. Is it a VM?
I0918 03:04:43.557173       1 utils.go:56] Available ebpf metrics: [bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq]
I0918 03:04:43.557205       1 utils.go:57] Available counter metrics: []
I0918 03:04:43.557209       1 utils.go:58] Available cgroup metrics from cgroup: [cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used]
I0918 03:04:43.557230       1 utils.go:59] Available cgroup metrics from kubelet: [kubelet_cpu_usage kubelet_memory_bytes]
I0918 03:04:43.557326       1 model.go:177] Model Config CONTAINER_TOTAL: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557358       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557378       1 container_energy.go:109] Using the Ratio/DynPower Power Model to estimate Container Platform Power
I0918 03:04:43.557393       1 model.go:177] Model Config CONTAINER_COMPONENTS: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557408       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557425       1 container_energy.go:118] Using the Ratio/DynPower Power Model to estimate Container Component Power
I0918 03:04:43.557440       1 model.go:177] Model Config PROCESS_TOTAL: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557452       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557460       1 process_power.go:108] Using the Ratio/DynPower Power Model to estimate Process Platform Power
I0918 03:04:43.557471       1 model.go:177] Model Config PROCESS_COMPONENTS: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557483       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557489       1 process_power.go:117] Using the Ratio/DynPower Power Model to estimate Process Component Power
I0918 03:04:43.557499       1 model.go:177] Model Config NODE_TOTAL: {ModelType:LinearRegressor ModelOutputType:AbsPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.565566       1 lr.go:183] LR Model (AbsPower): getWeightFromServer: <nil> (error: status not ok: 400 BAD REQUEST ({[bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used kubelet_cpu_usage kubelet_memory_bytes block_devices_used cpu_architecture] AbsPower acpi 1 true  }))
I0918 03:04:43.565833       1 lr.go:188] LR Model (AbsPower): loadWeightFromURLorLocal(): &map[platform:{{4067.51980453514 map[] map[kubelet_cpu_usage:{8.225074882327771 61.882611238231696 128.77011809213587} kubelet_memory_bytes:{9.011536046098989e+06 4.377864223762704e+14 11.4818854701994}]}}] (error: <nil>)
I0918 03:04:43.565868       1 model.go:120] Using Power Model AbsPower
I0918 03:04:43.565876       1 node_platform_energy.go:54] Using the LinearRegressor/AbsPower Power Model to estimate Node Platform Power
I0918 03:04:43.565891       1 model.go:177] Model Config NODE_COMPONENTS: {ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/BPFOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.565914       1 node_component_energy.go:43] The updated Model Config : &{ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/BPFOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used kubelet_cpu_usage kubelet_memory_bytes block_devices_used] SystemMetaDataFeatureNames:[cpu_architecture] SystemMetaDataFeatureValues:[Cascade Lake]}
```

**Comment by jiangphcn** [comment]
New log looks like
```
```
root@node1:~# kc logs kepler-exporter-9qvhq -n kepler
Defaulted container "kepler-exporter" out of: kepler-exporter, estimator
I0918 03:04:42.231998       1 gpu.go:46] Failed to init nvml, err: could not init nvml: error opening libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0918 03:04:42.236549       1 qat.go:35] Failed to init qat-telemtry err: could not get qat status exit status 127
I0918 03:04:42.243547       1 exporter.go:158] Kepler running on version: v0.5.4-25-g47466bc-dirty
I0918 03:04:42.243577       1 config.go:270] using gCgroup ID in the BPF program: true
I0918 03:04:42.244115       1 config.go:272] kernel version: 5.15
I0918 03:04:42.244170       1 exporter.go:170] LibbpfBuilt: false, BccBuilt: true
I0918 03:04:42.244178       1 exporter.go:189] EnabledBPFBatchDelete: true
I0918 03:04:42.244212       1 rapl_msr_util.go:129] failed to open path /dev/cpu/0/msr: no such file or directory
I0918 03:04:42.244270       1 power.go:71] Unable to obtain power, use estimate method
I0918 03:04:42.244322       1 redfish.go:169] failed to get redfish credential file path
I0918 03:04:42.244349       1 power.go:56] use acpi to obtain power
I0918 03:04:42.244945       1 acpi.go:67] Could not find any ACPI power meter path. Is it a VM?
I0918 03:04:43.557173       1 utils.go:56] Available ebpf metrics: [bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq]
I0918 03:04:43.557205       1 utils.go:57] Available counter metrics: []
I0918 03:04:43.557209       1 utils.go:58] Available cgroup metrics from cgroup: [cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used]
I0918 03:04:43.557230       1 utils.go:59] Available cgroup metrics from kubelet: [kubelet_cpu_usage kubelet_memory_bytes]
I0918 03:04:43.557326       1 model.go:177] Model Config CONTAINER_TOTAL: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557358       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557378       1 container_energy.go:109] Using the Ratio/DynPower Power Model to estimate Container Platform Power
I0918 03:04:43.557393       1 model.go:177] Model Config CONTAINER_COMPONENTS: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557408       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557425       1 container_energy.go:118] Using the Ratio/DynPower Power Model to estimate Container Component Power
I0918 03:04:43.557440       1 model.go:177] Model Config PROCESS_TOTAL: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557452       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557460       1 process_power.go:108] Using the Ratio/DynPower Power Model to estimate Process Platform Power
I0918 03:04:43.557471       1 model.go:177] Model Config PROCESS_COMPONENTS: {ModelType:Ratio ModelOutputType:DynPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:false ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.557483       1 model.go:94] Using Power Model Ratio
I0918 03:04:43.557489       1 process_power.go:117] Using the Ratio/DynPower Power Model to estimate Process Component Power
I0918 03:04:43.557499       1 model.go:177] Model Config NODE_TOTAL: {ModelType:LinearRegressor ModelOutputType:AbsPower TrainerName: EnergySource:acpi SelectFilter: InitModelURL: InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0918 03:04:43.565566       1 lr.go:183] LR Model (AbsPower): getWeightFromServer: <nil> (error: status not ok: 400 BAD REQUEST ({[bpf_cpu_time_us bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used kubelet_cpu_usage kubelet_memory_bytes block_devices_used cpu_architecture] AbsPower acpi 1 true  }))
I0918 03:04:43.565833       1 lr.go:188] LR Model (AbsPower): loadWeightFromURLorLocal(): &map[platform:{{4067.51980453514 map[] map[kubelet_cpu_usage:{8.225074882327771 61.882611238231696 128.77011809213587} kubelet_memory_bytes:{9.011536046098989e+06 4.377864223762704e+14 11.4818854701994}]}}] (error: <nil>)
I0918 03:04:43.565868       1 model.go:120] Using Power Model AbsPower
I0918 03:04:43.565876       1 node_platform_energy.go:54] Using the LinearRegressor/AbsPower Power Model to estimate Node Platform Power
I0918 03:04:43.565891       1 model.go:177] Model Config NODE_COMPONENTS: {ModelType:EstimatorSidecar ModelOutputType:AbsPower TrainerName: EnergySource:rapl SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.6/nx12/std_v0.6/rapl/DynPower/BPFOnly/LinearRegressionTrainer_1.zip InitModelFilepath: IsNodePowerModel:true ContainerFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}

```

**Comment by jiangphcn** [comment]
@sunya-ch could you please take a look again?

**Review by rootfs — APPROVED** [review]

**Pull request merged**
