### PR TITLE
power: switch to model based estimator when the RAPL interface is not available

### PR DESCRIPTION
**Pull request by rootfs**
this should activate ML based estimator and fix the 0 counter issue on VM

cc @jichenjc @sallyom

### CODE REVIEW

**Comment by rootfs** [comment]
My VM (cpu model is `host-paththrough`) now has the following metrics
# Pod 
```
kepler_pod_energy_stat{block_devices_used="0",command="kube-sched",container_name="kube-scheduler",curr_bytes_read="0",curr_bytes_writes="0",curr_cache_miss="259419",curr_container_cpu_usage_seconds_total="0",curr_container_memory_working_set_bytes="0",curr_cpu_cycles="28983235",curr_cpu_instr="22146529",curr_cpu_time="0",pod_name="kube-scheduler-localhost.localdomain",pod_namespace="kube-system",total_bytes_read="0",total_bytes_writes="0",total_cache_miss="2448055",total_container_cpu_usage_seconds_total="556",total_container_memory_working_set_bytes="39395328",total_cpu_cycles="209800562",total_cpu_instr="131415256",total_cpu_time="0"} 5326
```
# Node
```
kepler_node_core_joules_total{instance="localhost.localdomain",package="0",source="rapl"} 0.005
kepler_node_dram_joules_total{instance="localhost.localdomain",package="0",source="rapl"} 0.001
kepler_node_energy_stat{cpu_architecture="unknown",node_block_devices_used="0",node_curr_bytes_read="0",node_curr_bytes_writes="0",node_curr_cache_miss="0",node_curr_container_cpu_usage_seconds_total="0",node_curr_container_memory_working_set_bytes="0",node_curr_cpu_cycles="0",node_curr_cpu_instr="0",node_curr_cpu_time="0",node_curr_energy_in_core_joule="0",node_curr_energy_in_dram_joule="0",node_curr_energy_in_gpu_joule="0",node_curr_energy_in_other_joule="0",node_curr_energy_in_pkg_joule="0",node_curr_energy_in_uncore_joule="0",node_name="localhost.localdomain"} 0
kepler_node_nodeInfo{cpu_architecture="unknown"} 1
kepler_node_other_host_components_joules_total{instance="localhost.localdomain"} 0
kepler_node_package_energy_millijoule{core="0",dram="0",instance="localhost.localdomain",pkg_id="0",uncore="0"} 0
kepler_node_package_joules_total{instance="localhost.localdomain",package="0",source="rapl"} 0.008
kepler_node_platform_joules_total{instance="localhost.localdomain",source="acpi"} 0
kepler_node_uncore_joules_total{instance="localhost.localdomain",package="0",source="rapl"} 0
```

**Review by sunya-ch — CHANGES_REQUESTED** [review]
This case may not cover when the msr (and any future power implementation if developed) is capable. 
I think we may keep using IsSystemCollectionSupported but the dummy should return false by default not true.
https://github.com/sustainable-computing-io/kepler/blob/3f31bbd0ffd52cbfcb45d6cfb7948933787de5a8/pkg/power/components/source/dummy.go#L21

**Comment by rootfs** [comment]
@sunya-ch thanks for #390, I updated the PR using your suggestion

**Review by sunya-ch — APPROVED** [review]
/lgtm

**Pull request merged**
