### PR TITLE
feat: Export validation result as json object.

### PR DESCRIPTION
**Pull request by husky-parul**

### CODE REVIEW

**Comment by sthaha** [comment]
@husky-parul , could you please shed some light why this feature is needed?

**Comment by dave-tucker** [comment]
Another big +1 for JSON Output 🎉 I do not have strong opinions on how you do it.

The main usecase for me would be making the reports website that gets generated a lot more user friendly.

Using a [glob](https://www.npmjs.com/package/glob) package, you can easily load all JSON result files and use [ChartJS](
https://www.chartjs.org/docs/latest/samples/line/line.html) to draw some charts - i.e MASE/MSE trend over time.

Markdown tables are nice, but with a little more effort we could have tables that could be filtered/sorted etc...
and doing so would update the charts. This would let you produce a chart between two points - so you could see the trend from one release to another.

**Comment by sthaha** [comment]
@KaiyiLiu1234 @dave-tucker , +1 to adding json output if there is a requirement. 
@husky-parul , since we are adding a third reporter. Lets do that in a bit more maintainable way. I will submit a small change that should allow adding a new reporter for X format.

**Comment by sthaha** [comment]
@husky-parul could you please rebase this on to latest main? With the new changes, a dump of `TestResult` may suffice.

**Comment by husky-parul** [comment]
@sthaha 
PTAL

**Comment by husky-parul** [comment]
> > @husky-parul , could you please shed some light why this feature is needed?
> 
> Overall, I believe this is a very good solution to add. There are limitations with validation result output for the validator as it only outputs error metrics as a text file. For issue [66](https://github.com/sustainable-computing-io/kepler-metal-ci/issues/66), parsing the outputted text file from Report Class to acquire just the error metrics would be sub optimal. JSON would definitely be easier to operate on from the kepler-metal-ci side. That said, I think we should maybe pursue this differently.
> 
> I don’t think outputting all the metrics in JSON file is necessary because that is beyond the scope of the validator. Rather I propose a solution where Report is made into a generic abstract class. To make new types of reports like JSONReport or OverallMetricReport (This will store all the mean error metrics completed in a test. I will use this to solve [66](https://github.com/sustainable-computing-io/kepler-metal-ci/issues/66)). This way, there are a variety of different types of reports that can be saved as files and easily used depending on the circumstance. Note Report should only handle error metric outputs. What are your thoughts? @sthaha @husky-parul . Let me know if I misunderstood anything.

I agree. I tried to keep the json as limited as possible. For now an example json created by the module looks like this

```
{
  "file_path": "/tmp/validator-v0.2-2317-g2a4f858b/v0.2-2317-g2a4f858b.json",
  "build_info": [
    "{\"arch\": \"amd64\", \"branch\": \"main\", \"instance\": \"vm:9100\", \"job\": \"vm\", \"os\": \"linux\", \"revision\": \"52572fad497cd15fbc58efa7e682ecdcac799d55\", \"version\": \"v0.7.11-22-g52572fad\"}",
    "{\"arch\": \"amd64\", \"branch\": \"validator\", \"instance\": \"kepler-metal:8888\", \"job\": \"metal\", \"os\": \"linux\", \"revision\": \"006370e4ae63a11f21bc2fd7543a73e915cc1fa0\", \"version\": \"metal\"}"
  ],
  "node_info": [
    "{\"components_power_source\": \"estimator\", \"cpu_architecture\": \"Golden Cove\", \"instance\": \"vm:9100\", \"job\": \"vm\", \"platform_power_source\": \"none\", \"source\": \"os\"}",
    "{\"components_power_source\": \"rapl-sysfs\", \"cpu_architecture\": \"Gracemont\", \"instance\": \"kepler-metal:8888\", \"job\": \"metal\", \"platform_power_source\": \"none\", \"source\": \"os\"}"
  ],
  "machine_spec": [
    {
      "type": "host",
      "model": "12th Gen Intel(R) Core(TM) i7-1280P",
      "cores": "20",
      "threads": "2",
      "sockets": "1",
      "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities",
      "dram": "32556412 kB"
    },
    {
      "type": "vm",
      "model": "12th Gen Intel(R) Core(TM) i7-1280P",
      "cores": "8",
      "threads": "1",
      "sockets": "8",
      "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni arat vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize flush_l1d arch_capabilities",
      "dram": "8126004 kB"
    }
  ],
  "result": [
    {
      "metric-name": "platform_dynamic",
      "value": {
        "mse": 2283.612427239951,
        "mape": 100.0,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "package_dynamic",
      "value": {
        "mse": 0.0041044999999998825,
        "mape": 100.0,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "core_dynamic",
      "value": {
        "mse": 0.0034312400000000246,
        "mape": 100.0,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "dram_dynamic",
      "value": {
        "mse": 0.0,
        "mape": NaN,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "platform_idle",
      "value": {
        "mse": 2963.779604359818,
        "mape": 713.6663132551777,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "package_idle",
      "value": {
        "mse": 4128.229551699842,
        "mape": 209289.8438163121,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "core_idle",
      "value": {
        "mse": 4130.632899999841,
        "mape": 535583.333333324,
        "status": "mape passed: True, mse passed: True"
      }
    },
    {
      "metric-name": "dram_idle",
      "value": {
        "mse": 169.88515600000355,
        "mape": Infinity,
        "status": "mape passed: True, mse passed: True"
      }
    }
  ]
}
```

And the chart displays just the MSE and MAPE for all the metrics 
Screenshot from 2024-08-07 12-14-18

**Review by sthaha — APPROVED** [review]

**Pull request merged**
