### PR TITLE
chore: Remove cGroupMetrics

### PR DESCRIPTION
**Pull request by dave-tucker**
This is marked as deprecated in comments.
This commit removes them for good.

### CODE REVIEW

**Comment by dave-tucker** [comment]
30s CPU Profiles

Before:
Screenshot 2024-06-07 at 15 48 32


After:
Screenshot 2024-06-07 at 15 46 42

TL;DR reduces time spent in `Collector.Update` from 70ms to 50ms.

**Review by sthaha — APPROVED** [review]

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@dave-tucker it is ready to merge after rebase

**Comment by sunya-ch** [comment]
I have one concern about the old kernel version support. 
According to https://github.com/sustainable-computing-io/kepler/issues/1483, the current BPF source seems not available for the kernel older than 5.12. Are we expecting to provide the cgroups metrics instead of the BPF source in that case? Or we are going to provide optional BPF solution for the old kernel version later.

**Comment by dave-tucker** [comment]
> I have one concern about the old kernel version support. According to #1483, the current BPF source seems not available for the kernel older than 5.12. Are we still expecting to provide the cgroups metrics instead of the BPF source in that case? Or we are going to provide optional BPF solution for the old kernel version later.

I agree that potentially using cgroup metrics would be fine to support kernels < 5.12 (or whatever the minimum kernel version supported by our eBPF probes is). However, this is what's populated by each one today:

```go
const (
	// Populated by eBPF
	CPUCycle       = "cpu_cycles"
	CPURefCycle    = "cpu_ref_cycles"
	CPUInstruction = "cpu_instructions"
	CacheMiss      = "cache_miss"
	CPUTime       = "bpf_cpu_time_ms"
	PageCacheHit  = "bpf_page_cache_hit"
	IRQNetTXLabel = "bpf_net_tx_irq"
	IRQNetRXLabel = "bpf_net_rx_irq"
	IRQBlockLabel = "bpf_block_irq"

	// cgroup - cgroup package
	CgroupfsMemory       = "cgroupfs_memory_usage_bytes"
	CgroupfsKernelMemory = "cgroupfs_kernel_memory_usage_bytes"
	CgroupfsTCPMemory    = "cgroupfs_tcp_memory_usage_bytes"
	CgroupfsCPU          = "cgroupfs_cpu_usage_us"
	CgroupfsSystemCPU    = "cgroupfs_system_cpu_usage_us"
	CgroupfsUserCPU      = "cgroupfs_user_cpu_usage_us"
	CgroupfsReadIO       = "cgroupfs_ioread_bytes"
	CgroupfsWriteIO      = "cgroupfs_iowrite_bytes"
	BytesReadIO          = "bytes_read"
	BytesWriteIO         = "bytes_writes"
	BlockDevicesIO       = "block_devices_used"
)
```

Ideally we'd have a `ProcessMetricsCollector` interface where eBPF/CGroup are options where we could pick whichever option is supported.

As the current code stands though, none of the gathered metrics via cgroup are used by the model for estimation.

**Pull request merged**
